[package]
name = "register-program"
version = "0.1.0"
edition = "2021"

[dependencies]
solana-program = "2.0.3"
borsh = "1.5.1"
borsh-derive = "1.5.1"
serde_json = "1.0.108"

[lib]
crate-type = ["cdylib"]